### ISSUE TITLE
Version 1.0.0 has not been correctly pushed to PyPI

### ISSUE THREAD

**Issue by VladimirSvoboda** [MapIV/pypcd4#17]
As visible on:
- the logs of the action https://github.com/MapIV/pypcd4/actions/runs/9092205859/job/24988412629
- on PyPI https://pypi.org/project/pypcd4/#history

the release `1.0.0` has been wrongly pushed to pypy as version `1.0.1.dev0`

**Comment by urasakikeisuke** [comment]
Thanks for the heads up. Not sure what went wrong with the GitHub Action, I will fix it eventually.

**Comment by urasakikeisuke** [comment]
It will take some time to resolve this issue, so I have manually published v1.0.0 to PyPI for now. Thank you for your contribution and for reporting the issue.
Please check https://pypi.org/project/pypcd4/1.0.0/.
